# ⚡ Polymarket Arbitrage Bot Configuration

# Application
app:
  name: "Polymarket Arbitrage Tool"
  version: "1.0.0"
  window_width: 1000
  window_height: 750

# Polymarket API Endpoints
polymarket:
  gamma_api: "https://gamma-api.polymarket.com"
  clob_api: "https://clob.polymarket.com"
  
# Trading Settings
trading:
  min_profit_threshold: 0.01  # Minimum profit to execute ($0.01)
  trading_fee: 0.02           # Polymarket trading fee (2%)
  gas_estimate: 0.01          # Estimated gas cost ($0.01)
  
# Demo Mode
demo:
  initial_balance: 1000.0     # Starting balance (fake money)
  
# UI Settings
ui:
  auto_execute: true          # Auto-execute when arbitrage detected
  
# Logging
logging:
  level: "INFO"               # DEBUG, INFO, WARNING, ERROR
  log_to_file: true
